apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: vaultwarden
  name: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vaultwarden
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: vaultwarden
    spec:
      containers:
        - env:
            - name: ADMIN_TOKEN
              value: Dennik_vergibt_Passwörter_01
            - name: DOMAIN
              value: https://vaultwarden.borgwardtech.net
            - name: EXTENDED_LOGGING
              value: "true"
            - name: LOG_FILE
              value: /data/vaultwarden.log
            - name: LOG_LEVEL
              value: warn
            - name: PASSWORD_ITERATIONS
              value: "500000"
            - name: SENDS_ALLOWED
              value: "true"
            - name: SIGNUPS_ALLOWED
              value: "true"
            - name: SIGNUPS_VERIFY
              value: "true"
            - name: SMTP_FROM
              value: ncborgwardtech@gmail.com
            - name: SMTP_FROM_NAME
              value: Vaultwarden
            - name: SMTP_HOST
              value: smtp.gmail.com
            - name: SMTP_PASSWORD
              value: gdjektulgzmpphxt
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_SECURITY
              value: starttls
            - name: SMTP_TIMEOUT
              value: "15"
            - name: SMTP_USERNAME
              value: ncborgwardtech@gmail.com
            - name: TZ
              value: Europe/Berlin
            - name: WEBSOCKET_ENABLED
              value: "true"
          image: vaultwarden/server:latest
          name: vaultwarden
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: vaultwarden-vol0
      restartPolicy: Always
      volumes:
        - name: vaultwarden-vol0
          persistentVolumeClaim:
            claimName: vaultwarden-vol0
status: {}
