---
kind: Service
apiVersion: v1
metadata:
  name: gitea-service
  namespace: gitea-repo
spec:
  selector:
    app: gitea
  ports:
  - name: gitea-http
    port: 80
    targetPort: 3000
  - name: gitea-ssh
    port: 22
  type: ClusterIP
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: git-tls
  namespace: gitea-repo
  annotations:
   #nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  # tls: 
  # - hosts: 
  #   - gitea.kubenet.lan
  #   secretName: gitea-tls-secret
  rules:
    - host: gitea.kubenet.lan
      http:
        paths:
          - backend:
              service:
                name: gitea-service
                port:
                  name: gitea-http
            path: /
            pathType: Prefix
