---
kind: Service
apiVersion: v1
metadata:
  name: gitea-service
  namespace: gitea-repo
spec:
  selector:
    app: gitea
  ports:
  - name: gitea-http
    port: 80
    targetPort: 3000
  - name: gitea-ssh
    port: 22
  type: LoadBalancer
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: git-ingress
  namespace: gitea-repo
  annotations:
spec:
  tls: 
  - hosts: 
    - gitea.kubenet.lan
  secretName: gitea-tls-secret
  defaultBackend:
    service:
      name: gitea-service
      port:
        number: 80
  ingressClassName: nginx
  rules:
    - host: gitea.kubenet.lan
      http:
        paths:
          - backend:
              service:
                name: gitea-service
                port:
                  number: 80
            path: /
            pathType: Prefix
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea-cert
  namespace: gitea-repo
spec:
  secretName: gitea-tls-secret
  issuerRef:
    name: local-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - gitea.kubenet.lan