apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea-cert
  namespace: gitea-repo
spec:
  secretName: gitea-tls-secret
  issuerRef:
    name: local-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - gitea.kubenet.lan