apiVersion: v1
kind: Namespace
metadata:
  name: stirling-pdf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '11'
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["10.1.2.34"],"port":80,"protocol":"TCP","serviceName":"stirling-pdf:stirling-pdf","allNodes":false}]
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"kompose.cmd":"kompose
      convert","kompose.version":"1.26.0
      (40646f47)"},"creationTimestamp":null,"labels":{"io.kompose.service":"stirling-pdf"},"name":"stirling-pdf","namespace":"stirling-pdf"},"spec":{"replicas":1,"selector":{"matchLabels":{"io.kompose.service":"stirling-pdf"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"annotations":{"kompose.cmd":"kompose
      convert","kompose.version":"1.26.0
      (40646f47)"},"creationTimestamp":null,"labels":{"io.kompose.service":"stirling-pdf"}},"spec":{"containers":[{"env":[{"name":"DOCKER_ENABLE_SECURITY","value":"false"}],"image":"frooodle/s-pdf:latest","name":"stirling-pdf","ports":[{"containerPort":8080}],"resources":{},"volumeMounts":[{"mountPath":"/usr/share/tesseract-ocr/4.00/tessdata","name":"stirling-pdf-vol0"},{"mountPath":"/configs","name":"stirling-pdf-vol1"},{"mountPath":"/customFiles/","name":"stirling-pdf-vol2"}]}],"restartPolicy":"Always","volumes":[{"name":"stirling-pdf-vol0","persistentVolumeClaim":{"claimName":"stirling-pdf-vol0"}},{"name":"stirling-pdf-vol1","persistentVolumeClaim":{"claimName":"stirling-pdf-vol1"}},{"name":"stirling-pdf-vol2","persistentVolumeClaim":{"claimName":"stirling-pdf-vol2"}}]}}},"status":{}}
  creationTimestamp: '2023-12-20T13:53:59Z'
  generation: 27
  labels:
    io.kompose.service: stirling-pdf
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kompose.cmd: {}
            f:kompose.version: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:io.kompose.service: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:type: {}
          f:template:
            f:metadata:
              f:annotations:
                .: {}
                f:kompose.cmd: {}
                f:kompose.version: {}
              f:labels:
                .: {}
                f:io.kompose.service: {}
            f:spec:
              f:containers:
                k:{"name":"stirling-pdf"}:
                  .: {}
                  f:env:
                    .: {}
                    k:{"name":"DOCKER_ENABLE_SECURITY"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":8080,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:protocol: {}
                  f:resources: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/configs"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                    k:{"mountPath":"/customFiles/"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                    k:{"mountPath":"/usr/share/tesseract-ocr/4.00/tessdata"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
              f:volumes:
                .: {}
                k:{"name":"stirling-pdf-vol0"}:
                  .: {}
                  f:name: {}
                  f:persistentVolumeClaim:
                    .: {}
                    f:claimName: {}
                k:{"name":"stirling-pdf-vol1"}:
                  .: {}
                  f:name: {}
                  f:persistentVolumeClaim:
                    .: {}
                    f:claimName: {}
                k:{"name":"stirling-pdf-vol2"}:
                  .: {}
                  f:name: {}
                  f:persistentVolumeClaim:
                    .: {}
                    f:claimName: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2023-12-20T13:53:59Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:field.cattle.io/publicEndpoints: {}
        f:spec:
          f:replicas: {}
          f:template:
            f:metadata:
              f:namespace: {}
            f:spec:
              f:containers:
                k:{"name":"stirling-pdf"}:
                  f:ports:
                    k:{"containerPort":8080,"protocol":"TCP"}:
                      f:name: {}
      manager: rancher
      operation: Update
      time: '2024-02-05T21:14:38Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      manager: k3s
      operation: Update
      subresource: status
      time: '2024-02-05T21:15:39Z'
  name: stirling-pdf
  namespace: stirling-pdf
  resourceVersion: '50490447'
  uid: e85721e1-298b-457f-8dea-cde043c8b763
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: stirling-pdf
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: stirling-pdf
      namespace: stirling-pdf
    spec:
      containers:
        - env:
            - name: DOCKER_ENABLE_SECURITY
              value: 'false'
          image: frooodle/s-pdf:latest
          imagePullPolicy: Always
          name: stirling-pdf
          ports:
            - containerPort: 8080
              name: 8080tcp
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/share/tesseract-ocr/4.00/tessdata
              name: stirling-pdf-vol0
            - mountPath: /configs
              name: stirling-pdf-vol1
            - mountPath: /customFiles/
              name: stirling-pdf-vol2
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: stirling-pdf-vol0
          persistentVolumeClaim:
            claimName: stirling-pdf-vol0
        - name: stirling-pdf-vol1
          persistentVolumeClaim:
            claimName: stirling-pdf-vol1
        - name: stirling-pdf-vol2
          persistentVolumeClaim:
            claimName: stirling-pdf-vol2
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2024-01-09T17:07:21Z'
      lastUpdateTime: '2024-01-30T09:40:21Z'
      message: ReplicaSet "stirling-pdf-74cddd8945" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2024-02-05T21:15:39Z'
      lastUpdateTime: '2024-02-05T21:15:39Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
  observedGeneration: 27
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["10.1.2.34"],"port":80,"protocol":"TCP","serviceName":"stirling-pdf:stirling-pdf","allNodes":false}]
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
    kube-vip.io/loadbalancerIPs: 10.1.20.40
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"kompose.cmd":"kompose
      convert","kompose.version":"1.26.0
      (40646f47)"},"creationTimestamp":null,"labels":{"io.kompose.service":"stirling-pdf"},"name":"stirling-pdf","namespace":"stirling-pdf"},"spec":{"ports":[{"name":"80","port":80,"targetPort":8080}],"selector":{"io.kompose.service":"stirling-pdf"}},"status":{"loadBalancer":{}}}
    metallb.universe.tf/ip-allocated-from-pool: first-pool
  creationTimestamp: '2023-12-20T00:48:01Z'
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    implementation: kube-vip
    io.kompose.service: stirling-pdf
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kompose.cmd: {}
            f:kompose.version: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:io.kompose.service: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":80,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2023-12-20T00:48:01Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"service.kubernetes.io/load-balancer-cleanup": {}
      manager: kube-vip-cloud-provider
      operation: Update
      subresource: status
      time: '2023-12-20T14:32:36Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:kube-vip.io/loadbalancerIPs: {}
          f:labels:
            f:implementation: {}
      manager: kube-vip-cloud-provider
      operation: Update
      time: '2024-01-09T17:15:20Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:metallb.universe.tf/ip-allocated-from-pool: {}
        f:status:
          f:loadBalancer:
            f:ingress: {}
      manager: controller
      operation: Update
      subresource: status
      time: '2024-01-09T17:38:30Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:field.cattle.io/publicEndpoints: {}
        f:spec:
          f:allocateLoadBalancerNodePorts: {}
          f:externalTrafficPolicy: {}
          f:loadBalancerIP: {}
          f:type: {}
      manager: rancher
      operation: Update
      time: '2024-01-09T17:38:30Z'
  name: stirling-pdf
  namespace: stirling-pdf
  resourceVersion: '22054517'
  uid: 0c79f0f6-8e8f-428e-b59b-20d7c927d500
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.35.181
  clusterIPs:
    - 10.43.35.181
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 10.1.2.34
  ports:
    - name: '80'
      nodePort: 31338
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    io.kompose.service: stirling-pdf
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: stirling-pdf
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  rules:
    - host: pdf.kubenet.lan
      http:
        paths:
          - backend:
              service:
                name: stirling-pdf
                port:
                  number: 80
            path: /
            pathType: Prefix
